-- ====================================================================
-- MANPOWER CHAIN - SUPABASE DATABASE AND PRIVATE RESUME STORAGE SETUP
-- Run this script in the Supabase SQL Editor before using live mode.
-- Admin users must have app_metadata.role = "admin".
-- ====================================================================

CREATE TABLE IF NOT EXISTS public.applicants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_reference TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  alternate_phone TEXT,
  email TEXT UNIQUE,
  address TEXT,
  city TEXT NOT NULL,
  district TEXT NOT NULL,
  state TEXT NOT NULL,
  pincode TEXT,
  willing_to_relocate BOOLEAN NOT NULL DEFAULT false,
  education TEXT NOT NULL,
  course_name TEXT,
  institution_name TEXT,
  passing_year TEXT,
  certificate_available TEXT,
  work_type TEXT NOT NULL,
  preferred_role TEXT,
  experience_years INTEGER NOT NULL DEFAULT 0 CHECK (experience_years BETWEEN 0 AND 50),
  skills TEXT,
  availability TEXT NOT NULL,
  expected_salary NUMERIC(12, 2),
  resume_path TEXT,
  resume_original_name TEXT,
  resume_mime_type TEXT,
  resume_size_bytes BIGINT,
  resume_uploaded_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'new',
  consent_accepted_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Add new UX fields when upgrading an existing prototype table.
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS application_reference TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS alternate_phone TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS pincode TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS willing_to_relocate BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS course_name TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS institution_name TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS passing_year TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS certificate_available TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS preferred_role TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS availability TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS expected_salary NUMERIC(12, 2);
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS resume_path TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS resume_original_name TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS resume_mime_type TEXT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS resume_size_bytes BIGINT;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS resume_uploaded_at TIMESTAMPTZ;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS consent_accepted_at TIMESTAMPTZ;
ALTER TABLE public.applicants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now());
ALTER TABLE public.applicants ALTER COLUMN email DROP NOT NULL;
ALTER TABLE public.applicants ALTER COLUMN state DROP DEFAULT;
ALTER TABLE public.applicants ALTER COLUMN status SET DEFAULT 'new';

-- Give legacy records a reference and map the original pending stage to the new workflow.
UPDATE public.applicants
SET application_reference = CONCAT('MC-LEGACY-', id)
WHERE application_reference IS NULL;

UPDATE public.applicants SET status = 'new' WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS applicants_application_reference_idx
  ON public.applicants (application_reference);
CREATE INDEX IF NOT EXISTS applicants_created_at_idx ON public.applicants (created_at DESC);
CREATE INDEX IF NOT EXISTS applicants_status_idx ON public.applicants (status);
CREATE INDEX IF NOT EXISTS applicants_location_idx ON public.applicants (state, district);
CREATE INDEX IF NOT EXISTS applicants_work_type_idx ON public.applicants (work_type);

ALTER TABLE public.applicants ENABLE ROW LEVEL SECURITY;

-- Limit Data API privileges; RLS policies below determine which permitted rows are allowed.
REVOKE ALL ON public.applicants FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.applicants_id_seq FROM anon, authenticated;
GRANT INSERT ON public.applicants TO anon, authenticated;
GRANT SELECT, UPDATE ON public.applicants TO authenticated;
GRANT USAGE ON SEQUENCE public.applicants_id_seq TO anon, authenticated;

DROP POLICY IF EXISTS "Allow public insert" ON public.applicants;
DROP POLICY IF EXISTS "Allow authenticated read" ON public.applicants;
DROP POLICY IF EXISTS "Allow authenticated update" ON public.applicants;
DROP POLICY IF EXISTS "Public can submit applications" ON public.applicants;
DROP POLICY IF EXISTS "Admins can read applicants" ON public.applicants;
DROP POLICY IF EXISTS "Admins can update applicants" ON public.applicants;

CREATE POLICY "Public can submit applications"
  ON public.applicants
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (status = 'new' AND consent_accepted_at IS NOT NULL);

CREATE POLICY "Admins can read applicants"
  ON public.applicants
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

CREATE POLICY "Admins can update applicants"
  ON public.applicants
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  WITH CHECK ((SELECT auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Private resumes. Bucket restrictions reject non-document files and files over 5 MB.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'applicant-resumes',
  'applicant-resumes',
  false,
  5242880,
  ARRAY[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Applicants can upload resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admins can read resumes" ON storage.objects;

CREATE POLICY "Applicants can upload resumes"
  ON storage.objects
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'applicant-resumes');

CREATE POLICY "Admins can read resumes"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'applicant-resumes'
    AND (SELECT auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
