-- ====================================================================
-- MANPOWER CHAIN - FULL DATABASE AND ADMIN ACCOUNT SETUP SCRIPT
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ====================================================================

-- Enable pgcrypto extension for secure password hashing
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Create public.applicants table
CREATE TABLE IF NOT EXISTS public.applicants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_reference TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  alternate_phone TEXT,
  email TEXT UNIQUE,
  address TEXT,
  city TEXT NOT NULL,
  district TEXT NOT NULL,
  state TEXT NOT NULL,
  pincode TEXT,
  willing_to_relocate BOOLEAN NOT NULL DEFAULT false,
  education TEXT NOT NULL,
  course_name TEXT,
  institution_name TEXT,
  passing_year TEXT,
  certificate_available TEXT,
  work_type TEXT NOT NULL,
  preferred_role TEXT,
  experience_years INTEGER NOT NULL DEFAULT 0 CHECK (experience_years BETWEEN 0 AND 50),
  skills TEXT,
  availability TEXT NOT NULL,
  expected_salary NUMERIC(12, 2),
  resume_path TEXT,
  resume_original_name TEXT,
  resume_mime_type TEXT,
  resume_size_bytes BIGINT,
  resume_uploaded_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'new',
  consent_accepted_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create public.admin_users table
CREATE TABLE IF NOT EXISTS public.admin_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create indexes for applicants
CREATE UNIQUE INDEX IF NOT EXISTS applicants_application_reference_idx ON public.applicants (application_reference);
CREATE INDEX IF NOT EXISTS applicants_created_at_idx ON public.applicants (created_at DESC);
CREATE INDEX IF NOT EXISTS applicants_status_idx ON public.applicants (status);
CREATE INDEX IF NOT EXISTS applicants_location_idx ON public.applicants (state, district);
CREATE INDEX IF NOT EXISTS applicants_work_type_idx ON public.applicants (work_type);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.applicants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 5. Revoke public/anonymous access and grant restricted api access
REVOKE ALL ON public.applicants FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.applicants_id_seq FROM anon, authenticated;
GRANT INSERT ON public.applicants TO anon, authenticated;
GRANT SELECT, UPDATE ON public.applicants TO authenticated;
GRANT USAGE ON SEQUENCE public.applicants_id_seq TO anon, authenticated;

-- 6. Setup RLS Policies for admin_users
DROP POLICY IF EXISTS "Authenticated users can check admin status" ON public.admin_users;
CREATE POLICY "Authenticated users can check admin status"
  ON public.admin_users FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- 7. Setup RLS Policies for applicants (querying admin_users table)
DROP POLICY IF EXISTS "Public can submit applications" ON public.applicants;
DROP POLICY IF EXISTS "Admins can read applicants" ON public.applicants;
DROP POLICY IF EXISTS "Admins can update applicants" ON public.applicants;

CREATE POLICY "Public can submit applications"
  ON public.applicants
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (status = 'new' AND consent_accepted_at IS NOT NULL);

CREATE POLICY "Admins can read applicants"
  ON public.applicants
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can update applicants"
  ON public.applicants
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE user_id = auth.uid()
    )
  );

-- 8. Create the private Storage Bucket for resumes
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'applicant-resumes',
  'applicant-resumes',
  false,
  5242880,
  ARRAY[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 9. Setup Storage RLS Policies (querying admin_users table)
DROP POLICY IF EXISTS "Applicants can upload resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admins can read resumes" ON storage.objects;

CREATE POLICY "Applicants can upload resumes"
  ON storage.objects
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'applicant-resumes');

CREATE POLICY "Admins can read resumes"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'applicant-resumes'
    AND EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE user_id = auth.uid()
    )
  );

-- 10. Automatically seed the Admin Account: lsabish2001@gmail.com / Sabish@
DO $$
DECLARE
  new_admin_id UUID := gen_random_uuid();
  admin_email TEXT := 'lsabish2001@gmail.com';
  admin_password_hash TEXT := crypt('Sabish@', gen_salt('bf'));
BEGIN
  -- Check if user already exists in auth.users
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = admin_email) THEN
    
    -- Insert user into auth.users schema
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      aud,
      role,
      created_at,
      updated_at,
      confirmation_token,
      recovery_token,
      email_change_token_new,
      email_change
    ) VALUES (
      new_admin_id,
      '00000000-0000-0000-0000-000000000000',
      admin_email,
      admin_password_hash,
      now(),
      '{"provider":"email","providers":["email"]}',
      '{}',
      'authenticated',
      'authenticated',
      now(),
      now(),
      '',
      '',
      '',
      ''
    );

    -- Insert corresponding identity record so login flow recognizes it
    INSERT INTO auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      provider_id,
      last_sign_in_at,
      created_at,
      updated_at
    ) VALUES (
      new_admin_id,
      new_admin_id,
      jsonb_build_object('sub', new_admin_id, 'email', admin_email, 'email_verified', true),
      'email',
      admin_email,
      now(),
      now(),
      now()
    );

    -- Link user as admin in admin_users table
    INSERT INTO public.admin_users (user_id, email)
    VALUES (new_admin_id, admin_email);

    RAISE NOTICE 'Admin user created successfully!';
  ELSE
    -- If user already exists in auth, make sure they exist in the admin_users list
    INSERT INTO public.admin_users (user_id, email)
    SELECT id, email FROM auth.users WHERE email = admin_email
    ON CONFLICT (email) DO NOTHING;
    
    -- Update their password to Sabish@ just in case
    UPDATE auth.users 
    SET encrypted_password = admin_password_hash
    WHERE email = admin_email;

    RAISE NOTICE 'Admin user already exists. Verified admin table entry and updated password.';
  END IF;
END $$;
